name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest

    env:
      Solution_Name: RxFramework  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Build the Project
    - name: Build project
      run: dotnet build

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
