name: Create release
on: 
  push:
    branches:
      - release/*

jobs:
  createRelease:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
            
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      
    - name: Create nuget package
      run: .\.github\workflows\scripts\createNugetPackage.ps1 .

    - name: publish nuget
      run: dotnet nuget push "**/*.nupkg" -s 'https://api.nuget.org/v3/index.json' -k ${{ secrets.NUGET_ORG }}
