name: Create release
on: 
  push:
    branches:
      - release/*

jobs:
  createRelease:
    runs-on: windows-latest

    steps:
      - nam: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main     

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Create nuget package
        run: .\.github\workflows\scripts\createNugetPackage.ps1

      - name: publish nuget
        run: dotnet nuget push "**/*.nupkg" -s https://nuget.pkg.github.com/Reactive-Applications/index.json -k ${GITHUB_TOKEN}
